### ISSUE TITLE
Remove the Time from the footer

### ISSUE THREAD

**Issue by gugavaro** [kasunkv/slack-notification#8]
If you post a message with footer, the time is repeated on the app line (very first line) and the footer line (very last line), it i just the same info in 2 places.
It should either be removed or have an option to not include that on the notification.

**Comment by kasunkv** [comment]
@gugavaro Can you provide a screenshot with any important stuff removed so I can see clearly what the problem is.

**Comment by kasunkv** [comment]
@gugavaro I think i understand what you are referring to. I'll make the change.

**Comment by gugavaro** [comment]
Thank you!

**Comment by kasunkv** [comment]
@gugavaro I have released v2.3.1 of the task that supports disabling the timestamp in the footer.
![footer-timestamp](https://user-images.githubusercontent.com/4517739/40191700-dfdd8478-5a1f-11e8-8446-e2a25e0b8e28.PNG)
You should see a checkbox to toggle this. Its on by default. You can turn it off to remove the timestamp..

**Comment by gugavaro** [comment]
It is still not showing to me. was it already published?
Do I need to uninstall and re-install the plugin form the marketplace?

**Comment by kasunkv** [comment]
Since it's not a major version update, it should automatically show up. Are you using VSTS or TFS?

**Comment by gugavaro** [comment]
VSTS, not showing yet for me.

**Comment by gugavaro** [comment]
It is on, thanks for fixing it!
